version: "3.3"

  # Services
services:

  # Mariadb
  mariadb:
    image: mariadb:10.8
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - mariadbdata:/var/lib/mysql
      - ./config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:rw
    environment:
      MARIADB_DATABASE: wordpress
      MARIADB_ROOT_PASSWORD: root
    #restart: always

  # Phpmyadmin
  phpmyadmin:
    image: phpmyadmin:5.2-apache
    ports:
      - 127.0.0.1:8080:80
    volumes:
      - phpmyadmindata:/var/www/html
    environment:
      PMA_HOST: mariadb:3306
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mariadb
    #restart: always

  # Wordpress
  wordpress:
    image: wordpress:6.0-apache
    ports:
      - 127.0.0.1:80:80
    volumes:
      - wpdata:/var/www/html
      - ./wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_CONFIG_EXTRA: define( 'FS_METHOD', 'direct' );
    depends_on:
      - mariadb
    #restart: always

  # Wordpress CLI
  cli:
    image: wordpress:cli-2.6
    volumes:
      - wpdata:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
    depends_on:
      - wordpress
      - mariadb
    #restart: always

# Volumes
volumes:
  mariadbdata:
  phpmyadmindata:
  wpdata:
