version: "3.3"

# Services
services:
  # docker exec -ti CONTAINER_NAME sh -c "chown -R www-data:www-data wp-content"
  # Wordpress
  wordpress:
    image: wordpress:5.9-apache
    ports:
      - 127.0.0.1:80:80
    volumes:
      - wpdata:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DEBUG: 1
    depends_on:
      - mariadb
      - phpmyadmin
    #restart: always
    networks:
      - wpnet

  # Mariadb
  mariadb:
    image: mariadb:10.7
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - ./config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - mariadbdata:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: root
    #restart: always
    networks:
      - wpnet

  # Phpmyadmin
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 127.0.0.1:8080:80
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mariadb
    #restart: always
    networks:
      - wpnet

# Network
networks:
  wpnet:

# Volumes
volumes:
  mariadbdata:
  phpmyadmindata:
  wpdata:
