version: "3.3"

services:
  mariadb:
    image: mariadb
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - mariadbdata:/var/lib/mysql
    environment:
      MARIADB_DATABASE: wordpress
      MARIADB_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 127.0.0.1:8080:80
    volumes:
      - phpmyadmindata:/var/www/html
    environment:
      PMA_HOST: mariadb:3306
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mariadb

  wordpress:
    image: wordpress
    ports:
      - 127.0.0.1:80:80
    volumes:
      - wpdata:/var/www/html
      - ./wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_CONFIG_EXTRA: define( 'FS_METHOD', 'direct' );
    depends_on:
      - mariadb

  cli:
    image: wordpress:cli
    volumes:
      - wpdata:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
    depends_on:
      - wordpress
      - mariadb

volumes:
  mariadbdata:
  phpmyadmindata:
  wpdata:
